apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eshop-web
  template:
    metadata:
      labels:
        app: eshop-web
    spec:
      containers:
      - name: eshop-web-container
        image: piichiboi109/eshopweb-k8s:v1.0.0  # Docker image ที่สร้างไว้
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-web-service
spec:
  selector:
    app: eshop-web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000
  type: LoadBalancer
